"""Shape-bias probe via a Vision Transformer (extends Sec 3.3 / 3.4).

Track 3 (mechanism) showed NKE perturbations destroy low-level *texture* far
faster than *shape*: the edge skeleton survives to large eps_l while GLCM texture
similarity collapses. If the human--model recognizability gap is really a
texture/shape effect (Geirhos et al. 2019), then a *shape-biased* recognizer
should read NKE images better than a texture-biased one at matched perturbation.

ViTs are markedly more shape-biased than CNNs (Naseer et al. 2021; Tuli et al.
2021). This experiment turns that into a falsifiable prediction and tests it two
ways on CIFAR-10:

  (A) Cross-recognizer matrix. For every source architecture we generate NKE
      images (white-box, label kept) and measure how accurately every *other*
      architecture still recognizes them (the generic-recognizer proxy of the
      human track, generalized to all pairs). Prediction: for a CNN-sourced NKE,
      the ViT recognizer should retain accuracy better than the second CNN.

  (B) ViT as source. Run the standard human/OOD/mechanism tracks with vit as the
      source model (done by run_all); here we just surface the headline
      recognizability curve for vit-sourced NKE for direct comparison.
"""
import json, os
import numpy as np
import torch
from . import config as C
from . import models as M
from . import human as H
from .attackset import build_stimset, EPS_GRID


def run(dataset="cifar10", variant="nmifgm", n=200):
    archs = list(M.ARCHS[dataset].keys())          # e.g. [resnet18, vgg11, vit]
    grid = EPS_GRID[dataset]

    # Build (or load cached) the shared stimulus set for every source arch, and
    # load every model once to serve as a recognizer.
    stimsets = {a: build_stimset(dataset, a, variant=variant, n=n) for a in archs}
    recmods = {a: M.load(dataset, a, "clean") for a in archs}
    edge_net = H.train_edge_recognizer(dataset)

    # (A) cross-recognizer matrix: R[eps][src][rec] = accuracy of recognizer `rec`
    #     on NKE images generated by source `src` (src's own correct samples).
    out = {"dataset": dataset, "variant": variant, "archs": archs, "grid": grid,
           "cross_recognizer": [], "shape_bias_contrast": []}
    for eps in grid:
        entry = {"eps_l": eps, "R": {}, "shape_proxy": {}}
        for src in archs:
            xa = stimsets[src]["levels"][eps]["nke"]
            y = stimsets[src]["y"]
            entry["R"][src] = {rec: H.generic_recognizer_acc(recmods[rec], xa, y)
                               for rec in archs}
            entry["shape_proxy"][src] = H.shape_proxy_acc(edge_net, xa, y, dataset)
        out["cross_recognizer"].append(entry)
        # readable log line
        msg = " | ".join(
            f"{src}->" + ",".join(f"{rec}:{entry['R'][src][rec]:.2f}" for rec in archs)
            for src in archs)
        print(f"  eps_l={eps:5.1f}  {msg}")

    # --- Retention normalisation. Raw cross-recognizer accuracy is confounded by
    #     each recognizer's clean accuracy (the ViT is a weaker base model). The
    #     fair quantity is RETENTION = acc_on_NKE / acc_on_that_source's_clean
    #     samples (the eps_l=0 row), i.e. how much of its *own* clean recognition
    #     a recognizer keeps as the perturbation grows.
    base = {(src, rec): out["cross_recognizer"][0]["R"][src][rec]
            for src in archs for rec in archs}   # eps_l==0 is grid[0]

    def retention(eps, src, rec):
        b = base[(src, rec)]
        e = next(r for r in out["cross_recognizer"] if r["eps_l"] == eps)
        return (e["R"][src][rec] / b) if b > 0 else None

    # (B) the load-bearing contrast, per eps: for each CNN source, does the
    #     shape-biased ViT recognizer RETAIN NKE recognition better than the other
    #     CNN? (retention-normalised; excludes the white-box self). This is the
    #     falsifiable shape-bias prediction.
    cnns = [a for a in archs if a != "vit"]
    if "vit" in archs:
        for eps in grid:
            row = {"eps_l": eps, "per_source": {}}
            deltas = []
            for src in cnns:
                other_cnn = [c for c in cnns if c != src]
                vit_ret = retention(eps, src, "vit")
                cnn_ret = float(np.mean([retention(eps, src, o) for o in other_cnn])) if other_cnn else None
                d = (vit_ret - cnn_ret) if (vit_ret is not None and cnn_ret is not None) else None
                row["per_source"][src] = {"vit_retention": vit_ret,
                                          "other_cnn_retention": cnn_ret,
                                          "vit_minus_cnn_retention": d}
                if d is not None:
                    deltas.append(d)
            row["mean_vit_minus_cnn_retention"] = float(np.mean(deltas)) if deltas else None
            out["shape_bias_contrast"].append(row)
            if deltas:
                print(f"  [contrast] eps_l={eps:5.1f} "
                      f"CNN-sourced NKE: ViT-retention minus CNN-retention = "
                      f"{np.mean(deltas):+.3f}")

    # (C) source specificity: mean cross-model retention of NKE *generated by* each
    #     source (averaged over all other-arch recognizers). Lower = more
    #     model-specific / off-manifold perturbations.
    out["source_specificity"] = []
    for eps in grid:
        row = {"eps_l": eps}
        for src in archs:
            rets = [retention(eps, src, rec) for rec in archs if rec != src]
            rets = [r for r in rets if r is not None]
            row[src] = float(np.mean(rets)) if rets else None
        out["source_specificity"].append(row)

    path = os.path.join(C.RESULTS_DIR, f"vit_shapebias_{dataset}.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=2)
    print(f"[saved] {path}")
    return out


if __name__ == "__main__":
    run()
